#!/bin/bash
#SBATCH --job-name=goudacell
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=04:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=32gb
#SBATCH --gres=gpu:1
#SBATCH --output=out/logs/goudacell-%j.out

# GoudaCell Batch Segmentation SLURM Script
#
# Usage (run from the repo root so out/logs/ exists):
#   sbatch --partition=<gpu-partition> scripts/run_segmentation.sh configs/segmentation_config.yaml
#
# No partition is set here: pass your cluster's GPU partition with --partition, or
# export SBATCH_PARTITION=<gpu-partition> (list partitions with: sinfo -o "%P %G").
#
# Configs generated by the notebook carry absolute input/output paths, so this
# script does not need to cd anywhere.
#
# GOUDACELL_ENV picks the conda env (default: goudacell).

# Fail on errors
set -e

# Check for config argument
if [ -z "$1" ]; then
    echo "Usage: sbatch scripts/run_segmentation.sh configs/segmentation_config.yaml"
    exit 1
fi

CONFIG_PATH="$(realpath "$1")"

# Activate conda environment
eval "$(conda shell.bash hook)"
conda activate "${GOUDACELL_ENV:-goudacell}"

# Print environment info
echo "================================================"
echo "GoudaCell Batch Segmentation"
echo "================================================"
echo "Date: $(date)"
echo "Host: $(hostname)"
echo "Config: ${CONFIG_PATH}"
echo "Python: $(which python)"
echo ""

# Check GPU
python -c "import torch; print(f'CUDA available: {torch.cuda.is_available()}'); print(f'GPU: {torch.cuda.get_device_name(0)}' if torch.cuda.is_available() else 'No GPU')"
echo ""

# Run segmentation
echo "Starting segmentation..."
goudacell segment "${CONFIG_PATH}"

echo ""
echo "================================================"
echo "Completed: $(date)"
echo "================================================"
